ekf_filter_node:
  ros__parameters:

    # Basic config
    use_sim_time: true
    two_d_mode: true
    publish_tf: true
    publish_acceleration: false

    # Frame names
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    # Input Odometry Source
    odom0: /vehicle/nav_odometry
    odom0_config: [true, true, true,     # position x, y, z
               true, true, true,     # orientation roll, pitch, yaw
               true, true, true,     # linear velocity x, y, z
               true, true, true,     # angular velocity roll, pitch, yaw
               false, false, false]  # acceleration (not provided)
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10

    # Process noise tuning (moderate values)
    process_noise_covariance: [
      0.05, 0,    0,    0,    0,    0,
      0,    0.05, 0,    0,    0,    0,
      0,    0,    0.05, 0,    0,    0,
      0,    0,    0,    0.01, 0,    0,
      0,    0,    0,    0,    0.01, 0,
      0,    0,    0,    0,    0,    0.01]

    # Output transform publishing frequency (optional)
    frequency: 30.0

